version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 5000:5000
  bs:
    build:
      context: bs
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./src:/code
