version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 5000:5000
  livereload:
    image: ocasta/livereload
    ports:
      - "35729:35729"
    volumes:
      - .:/usr/src/livereload-watch
      